### ISSUE TITLE
StatusBar Prop causes SystemUI FC && NavBar can't be enabled.

### ISSUE THREAD

**Issue by npjohnson** [CyanogenMod/android_device_asus_fugu#1]
When flashing your recommended GApps package (The Full Version) on any nightly since ~06/01(?), you are met with continuous SystemUI crashes. The fix is to remove the StatusBar enabling Prop, which negates the purpose of the Full GApps package.

Also, the NavBar is not enablable by normal means (adding qemu.hw.mainkeys=0 to build.prop).

**Comment by bmc08gt** [comment]
Is this still an issue on the latest nightly(statusbar)?

**Comment by bmc08gt** [comment]
Also please put this issue on JIRA if not already there.

**Comment by npjohnson** [comment]
Yes. It is.

On Fri, Aug 21, 2015 at 10:23 AM, Brandon McAnsh notifications@github.com
wrote:

> Is this still an issue on the latest nightly(statusbar)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CyanogenMod/android_device_asus_fugu/issues/1#issuecomment-133441253
> .

## 

Nolen Johnson

_Programmer: C, Java, Python, ACPI, HTML5_
_Web Designer_
_Graphic Designer ACA Certified in PhotoShop CS 5.1_
_Security Researcher_

**Comment by npjohnson** [comment]
I'm not sure how to go about this, do you have a reference as to how to do
so?

On Fri, Aug 21, 2015 at 10:24 AM, Brandon McAnsh <notifications@github.com>
wrote:

> Also please put this issue on JIRA if not already there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CyanogenMod/android_device_asus_fugu/issues/1#issuecomment-133441315>
> .
>



-- 
Nolen Johnson

*Programmer: C, Java, Python, ACPI, HTML5*
*Web Designer*
*Graphic Designer ACA Certified in PhotoShop CS 5.1*
*Security Researcher*
